baseurl: ''
url: 'https://hermesgamba.com'
name: 'Hermes Gamba'
author: Hermes Gamba
whatsapp: https://wa.me/573155786000
telefono: tel://+573155786000

markdown: kramdown

permalink: :slug

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

collections:
  posts:
    output: true
    permalink: "/:categories/:slug"