baseurl: ''
url: 'https://hermesgamba.com'
name: 'Hermes Gamba'
author: Hermes Gamba
whatsapp: https://api.whatsapp.com/send?phone=+573155786000&text=Hola!%20Estaba%20en%20la%20p%C3%A1gina%20web%20del%20doctor%20Gamba.%20Por%20favor,%20env%C3%ADame%20m%C3%A1s%20info%20sobre...
telefono: tel://+573155786000

markdown: kramdown

permalink: :slug

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

collections:
  posts:
    output: true
    permalink: "/:categories/:slug"